grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
  module_1:
    class: RandomForestClassification
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 12
      n_estimators:
      - 10
  module_2:
     class: KnearestNeighborsClassification
     module: sklearn.neighbors
     weights:
     - 'uniform'
     - 'distance'
     algorithm:
     - 'ball_tree'
     - 'kd_tree'
     - 'brute'
     - 'auto'
     params: 
       n_jobs: 5
     search_param_grid:
       leaf_size:
       - 4
       - 6
       - 8
       n_estimators:
       - 100
       - 200
       
        
          
     
     

        